### PR TITLE
couldnt update tn. maybe ingesting M ds with no content?

### PR DESCRIPTION
**Pull request by nhart**

### CODE REVIEW

**Comment by adam-vessey** [comment]
Just to make the link: Mirrors https://github.com/Islandora/islandora_solution_pack_entities/pull/68, for the release.

**Comment by nhart** [comment]
I don't believe so. I think what Donald reported is a 409 error.

**Comment by nhart** [comment]
I could be wrong though.

**Comment by nhart** [comment]
I'm thinking so.

**Pull request merged**
