### PR TITLE
ISLANDORA-2317 - Fix Scholar MADS Position options (Second pass)

### PR DESCRIPTION
**Pull request by bondjimbond**
**JIRA Ticket**: (https://jira.duraspace.org/browse/ISLANDORA-2317)

# What does this Pull Request do?

Changes the included MADS form to put spaces between the values in the select list for the Position element.

This was originally done in PR #128 but reverted because an update hook was needed and we were too close to the release to complete. Update hook has been added; I'm not sure what else is needed, so open to comments now.

# What's new?

No more weird CamelCase values like ProfessorEmeritus and GraduateStudent.

# How should this be tested?

- Create a Person object using the form. Under Position, select a two-word role.
- See that the Position value is in CamelCase
- Check out this branch
- Run update.php, check if update hook info is adequate
- Create a new Person object with two-word Position
- Hooray, it looks OK
- Edit the previous Person object. Update their name and save, see what happens to Position
- Edit again, change the Position, review the MADS XML.

# Interested parties
@Islandora/7-x-1-x-committers, @willtp87, @DonRichards

### CODE REVIEW

**Comment by DonRichards** [comment]
I'll do this one! Sorry I missed this.

**Review by DonRichards — APPROVED** [review]
Works as expected. When editing an existing entity, the old position value is dropped because of the string change but if it was set after this PR it works as expected. Before & after

**Comment by bryjbrown** [comment]
`Tat-or salad` Really, @DonRichards?

**Comment by bondjimbond** [comment]
Just a prod @DonRichards - 24 hours has passed, so are we ready for merge?

**Comment by bondjimbond** [comment]
@DonRichards No comments or complaints. Are we good to go?

**Review by rosiel — APPROVED** [review]

**Comment by DonRichards** [comment]
Sorry, I missed the merge.

**Comment by bondjimbond** [comment]
You still can @DonRichards

**Pull request merged**
