### PR TITLE
Update README to include transformed MADS.

### PR DESCRIPTION
**Pull request by rosiel**
**JIRA Ticket**: (https://jira.duraspace.org/browse/ISLANDORA-1486) - related, but does not fix.
# What does this Pull Request do?

Improves the README by demonstrating which CSV fields become which MADS fields.
# What's new?

A demo MADS record. And also updated the maintainer.
# How should this be tested?

n/a
# Additional Notes:

Forthcoming PR to improve multiple value handling should include an update to this, but as-is this is low-hanging documentation fruit.
# Interested parties

I can't find any of the conveners of the DIG or Zach Vowell on Github - if you know them please tag them.

### CODE REVIEW

**Comment by manez** [comment]
Since this is a documentation update, I think a release pull is also desirable? Tagging @dltj as README Auditor for Entities in 7.x-1.7

**Comment by rosiel** [comment]
Created PR #100 on 7.x-1.7.

**Comment by dltj** [comment]
This makes sense to me...thanks @rosiel.  @manez -- I don't have access to the Islandora repos; can you merge this pull request and #100, please?

**Comment by manez** [comment]
@dltj @rosiel you bet!

**Pull request merged**
