### PR TITLE
Update README maintainer

### PR DESCRIPTION
**Pull request by librarychik**
Change to Danny Lamb

Please delete this pull request. I noticed I left off the final parentheses and didn't know how to fix it without completing the pr.  sorry! I'll start over.  jb

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by librarychik** [comment]
Or let me know if you can fix it without me doing another pr.  thanks.

**Comment by manez** [comment]
@librarychik  if you edit your fork, the changes should be automatically added to this PR.

**Comment by librarychik** [comment]
I updated but don't see the changes pushed here...

**Comment by librarychik** [comment]
Got it, sorry for the confusion

**Comment by manez** [comment]
@librarychik ++

I'm pretty sure I learned how that works in exactly the same way, some release ago 😄

**Review by manez — APPROVED** [review]

**Pull request merged**
